version: '3'
services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    network_mode: 'host'
    depends_on:
      - certbot
  iplbetting_nestjs:
    container_name: nestjsapp
    build: ./nestjssetup
    ports:
      - '8081:8081'
    depends_on:
      - mysql
      - nginx
    networks:
      - mylocalnetwork
    expose:
      - 8081
    environment:
      - VIRTUAL_HOST:ipl.restroid.in
    restart: always
  mysql:
    container_name: mysql1
    image: mysql/mysql-server
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./db-data/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_DATABASE=iplbetting
      - MYSQL_USER=scott
      - MYSQL_PASSWORD=tiger
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    networks:
      - mylocalnetwork
  phpmyadmin:
    container_name: phpmyadmin1
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    networks:
      - mylocalnetwork
    environment:
      - PMA_HOST=mysql1
    depends_on:
      - mysql
    restart: always

networks:
  mylocalnetwork:
